postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      dbname: pokemon
      user: postgres
      password: postgres
      schema: pokemon
      